### ISSUE TITLE
Docker compose up, has problem building the project. i am guessing Dockerfile problem.

### ISSUE THREAD

**Issue by sagarishere** [nagaokayuji/nuxt-golang#27]
=> [app internal] load build context                                                                                                                                                                      0.0s
 => => transferring context: 689B                                                                                                                                                                          0.0s
 => CANCELED [nuxt 1/6] FROM docker.io/library/node:15.11.0-alpine@sha256:1aa4d551d84797a2df6261e4b6a78b849f6bd11b0dc94b7f2ddf0023fecd8261                                                                 0.0s
 => => resolve docker.io/library/node:15.11.0-alpine@sha256:1aa4d551d84797a2df6261e4b6a78b849f6bd11b0dc94b7f2ddf0023fecd8261                                                                               0.0s
 => => sha256:1aa4d551d84797a2df6261e4b6a78b849f6bd11b0dc94b7f2ddf0023fecd8261 1.43kB / 1.43kB                                                                                                             0.0s
 => => sha256:4661f1124b51280faa9029a1107d2a4a1c7eb23a1b7ec2391054c6fdc0bb4480 1.16kB / 1.16kB                                                                                                             0.0s
 => => sha256:3bf3e2dcc598c886a53ba9951ea5d7f52dbf757624e243063307432cc67cfd79 6.73kB / 6.73kB                                                                                                             0.0s
 => [nuxt internal] load build context                                                                                                                                                                     0.0s
 => => transferring context: 2.46kB                                                                                                                                                                        0.0s
 => CACHED [nuxt 2/6] WORKDIR /app                                                                                                                                                                         0.0s
 => CACHED [nuxt 3/6] COPY ./package.json /app                                                                                                                                                             0.0s
 => ERROR [nuxt 4/6] COPY ./package-lock.json /app                                                                                                                                                         0.0s
------
 > [nuxt 4/6] COPY ./package-lock.json /app:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 03af3e56-352b-471a-a1b0-9f5be48959cd::p1jsxafy3vvwnyf8p3mis417e: "/package-lock.json": not found

**Comment by joewilson27** [comment]
is it still open?

**Comment by sagarishere** [comment]
not anymore
